"""empty message

Revision ID: 3ecc19c7422f
Revises: 6e7f0ba33ea6
Create Date: 2022-02-17 13:07:32.324415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3ecc19c7422f"
down_revision = "6e7f0ba33ea6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_transactions_id"), "transactions", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
    # ### end Alembic commands ###
