"""empty message

Revision ID: 45f3d220d9a7
Revises: be55648f833e
Create Date: 2022-02-17 13:33:31.057300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "45f3d220d9a7"
down_revision = "be55648f833e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "account_no")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("account_no", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
