"""empty message

Revision ID: 4c89ead6942a
Revises: 3ecc19c7422f
Create Date: 2022-02-17 13:31:01.719725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4c89ead6942a"
down_revision = "3ecc19c7422f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "account_no")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("account_no", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
