"""empty message

Revision ID: 4fe25d8f57bf
Revises: 45f3d220d9a7
Create Date: 2022-02-17 13:33:43.258784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4fe25d8f57bf"
down_revision = "45f3d220d9a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("account_no", sa.BigInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "account_no")
    # ### end Alembic commands ###
