"""empty message

Revision ID: 55c2fa3f5f52
Revises: 4fe25d8f57bf
Create Date: 2022-02-17 13:59:34.380595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "55c2fa3f5f52"
down_revision = "4fe25d8f57bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transactions_id", table_name="transactions")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_transactions_id", "transactions", ["id"], unique=False)
    # ### end Alembic commands ###
