"""empty message

Revision ID: 6e7f0ba33ea6
Revises: 
Create Date: 2022-02-17 13:04:40.578034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6e7f0ba33ea6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.Unicode(), nullable=False),
        sa.Column("account_no", sa.BigInteger(), nullable=True),
        sa.Column("details", sa.String(length=500), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("withdrawal", sa.Float(), nullable=True),
        sa.Column("deposit", sa.Float(), nullable=True),
        sa.Column("balance", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    # ### end Alembic commands ###
