"""empty message

Revision ID: 73cdaa1893b7
Revises: 0d799f8b0ead
Create Date: 2022-02-17 14:07:11.566452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "73cdaa1893b7"
down_revision = "0d799f8b0ead"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "details", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column("date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column(
            "withdrawal",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deposit",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "balance",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("account_no", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="transactions_pkey"),
    )
    # ### end Alembic commands ###
