"""empty message

Revision ID: a5c41f90257b
Revises: 55c2fa3f5f52
Create Date: 2022-02-17 14:03:34.948266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a5c41f90257b"
down_revision = "55c2fa3f5f52"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "account_no")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("account_no", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
