"""empty message

Revision ID: be55648f833e
Revises: 4c89ead6942a
Create Date: 2022-02-17 13:31:36.847168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "be55648f833e"
down_revision = "4c89ead6942a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("account_no", sa.BigInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "account_no")
    # ### end Alembic commands ###
